### ISSUE TITLE
CLI: support output formats

### ISSUE THREAD

**Issue by ssoroka** [infrahq/infra#1969] opened 2022-05-13 14:41 UTC
commands like `infra keys add` output data that scripts are going to want. 

currently you can get the key with `infra keys add connector 2>&1 | grep Key | awk '{print $2}'`, but it would be much nicer to support output formats, perhaps with pathing.

eg:
```sh
$ infra keys add connector -o json
{"name": "connector-2022-05-13T14:34:48.702384", "key": "p1ER0KCi6g.WYZjJJ8CRZ8yFkub5kyRMSF3"}

$ infra keys add connector -o yaml
name: connector-2022-05-13T14:34:48.702384
key: p1ER0KCi6g.WYZjJJ8CRZ8yFkub5kyRMSF3

$ infra keys add connector -o json --path .key 
p1ER0KCi6g.WYZjJJ8CRZ8yFkub5kyRMSF3
```
Note the last one is `p1ER0KCi6g.WYZjJJ8CRZ8yFkub5kyRMSF3` and not `"p1ER0KCi6g.WYZjJJ8CRZ8yFkub5kyRMSF3"`; the former seems more helpful, so not sure if the path ends in a string if we should display the contents of the string instead of the json string object.

**Comment by dnephin** [comment] 2022-05-13 15:29
A flag to enable a machine readable format would be great! I believe this issue is a duplicate of #972, which has a bit of discussion already, so going to close this issue. A flag like `--format` seems like a great way to handle this. A short flag might be good as well, but generally in scripts we want to suggest using the long form of flags.

I think we should create a separate issue for `--path`. The [jq](https://stedolan.github.io/jq/) tool is widely used, and makes it really easy to fetch fields out of JSON (ex: `infra keys add --format json connector | jq  --raw-output .key`), so we can probably avoid adding that flag initially.

**Closed by dnephin** 2022-05-13 15:29 UTC
