### ISSUE TITLE
Crashloopbackoff when deploying postgres container on GKE

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3124] opened 2022-09-03 22:54 UTC
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
It contains a lost+found directory, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```

**Comment by yeshwanth1312** [comment] 2022-09-06 15:25
This occurs when creating in EKS as well

**Comment by djerfy** [comment] 2022-10-13 08:41
Caused by `lost+found` default directory when an external volume is created. Same problem on GKE ans Scaleway.
I can fix Helm chart if you want.

**Comment by mxyng** [comment] 2022-11-02 00:37
Thanks for the pointer! We are currently working on a new set of Helm charts which will replace the ones in the this repo. This will be addressed in the new chart.

**Closed** 2022-11-04 01:33 UTC
Labels: kind/bug, area/deploy
