### ISSUE TITLE
Creating a grant twice yields `201` status code and a body with an empty ID

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2359] opened 2022-06-21 23:00 UTC
Example body: 
```
{"id":"","created":null,"created_by":"9epo7kF7eN","updated":null,"group":"9jMQ9w1YmZ","privilege":"admin","resource":"docker-desktop"}
```

If a grant already exists it should error or return another code

More info: https://github.com/infrahq/infra/blob/12673ae42505593bff48e21db44eef24ddf82983/internal/server/data/grant.go#L17

**Comment by ssoroka** [comment] 2022-06-22 19:49
I think a big question is: _what does the client want to see?_ There's no action a client would have to take if a grant already exists: applying the same grant twice creates the exact same result: the user has access to something. Failing on duplicate would not be a useful result:
![taskfailedsuccesfully](https://user-images.githubusercontent.com/7130/175123273-24daeb24-944b-4ce6-b12f-6024a4ce1967.jpg)

Consider from the perspective of a script using the api to apply or revoke grants: if the grant change already exists in the desired state, we don't want the script or api calls to start failing: the script is working, not erroring.

Closing this as intended behavior

**Closed by ssoroka** 2022-06-22 19:49 UTC
Labels: kind/bug, area/api
