### ISSUE TITLE
ui: okta icon is incorrect on the login page

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#2489] opened 2022-07-05 17:37 UTC
![Image](https://user-images.githubusercontent.com/63033505/177384940-cabe578f-2661-43e9-9b23-200005e0e12f.png)

**Comment by BruceMacD** [comment] 2022-07-06 12:56
I believe this could be from a bad migration on our dev cluster

**Comment by dkulchinsky** [comment] 2022-07-14 23:54
@BruceMacD I noticed the same after upgrading from 0.13.5 to 0.13.6

![Screenshot_20220714-195301_Chrome](https://user-images.githubusercontent.com/61992380/179119982-617a3e59-c7df-4217-89e9-5c38cb00bc40.jpg)

**Comment by BruceMacD** [comment] 2022-07-28 14:27
It seems like this was caused by a change to our config format and can be fixed by specifying the provider kind in config:
```
providers:
      - name: okta
        url: example.okta.com
        clientID: 0aaa
        clientSecret: bbb_
        kind: okta
```

Please let me know if the issue persists.

**Closed by BruceMacD** 2022-07-28 14:27 UTC
Labels: kind/bug, area/ui

**Comment by dkulchinsky** [comment] 2022-07-29 03:43
> It seems like this was caused by a change to our config format and can be fixed by specifying the provider kind in config:
> 
> ```
> providers:
>       - name: okta
>         url: example.okta.com
>         clientID: 0aaa
>         clientSecret: bbb_
>         kind: okta
> ```
> 
> Please let me know if the issue persists.

that did it, thanks!
