### ISSUE TITLE
cli: Windows CLI new line does not display correctly

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#2011] opened 2022-05-19 21:12 UTC
## Describe the bug
When using the Infra CLI on Windows new lines are not always properly displayed.

## Expected behavior
The CLI output matches *nix behavior.

## Screenshots
![image(1)](https://user-images.githubusercontent.com/5853428/169405579-2f9efe5f-52d2-4d25-ada6-9532bc42364c.png)

## Environment

```
$ infra version
 Client: 0.13.0
 Server: 0.13.0
```

## Additional context
Observed in Windows Powershell (terminal).

**Comment by mxyng** [comment] 2022-06-08 19:06
This is an issue in `AlecAivazis/survey` where the cursor isn't being adjusted correctly. It's not a straightforward fix since the cursor implementation is very low level with far reaching effects. Fixing it for this introduces regression for other prompts. Closing for now

**Closed by mxyng** 2022-06-08 19:06 UTC
Labels: kind/bug, area/cli
