### ISSUE TITLE
Initial connected status takes 6 minutes

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3594] opened 2022-11-07 22:10 UTC
It takes 6 minutes for a connected cluster to show "connected"

**Comment by dnephin** [comment] 2022-11-07 22:55
I thought I had fixed this in 82ee11bd42c955b7e99b6344512f5c06ec1f10be, which would have been first released in 0.16.0. 

Does this reproduce with the latest connector? If we haven't released a new version of the helm chart it might be pinned to an older version of the image.

If this is still happening with 0.16.0 we should figure out why the changes to `CreateDestination` in 82ee11bd42c955b7e99b6344512f5c06ec1f10be do not work as expected.

**Comment by dnephin** [comment] 2022-11-07 22:58
Oh, at least part of the problem is that `API.UpdateDestination` clobbers the `LastSeenAt` status and sets it back to 0. That's at least part of the problem.

We added a special case for `CreatedAt`, but that's not enough.

I think a `PUT` may not be appropriate for this endpoint, at least not for a connector. It should be a `PATCH` that sets only the fields that we care about updating.

**Closed** 2022-11-10 16:39 UTC
Labels: kind/bug, area/api
