### ISSUE TITLE
Self hosted infra server on K8s ubuntu fails scheduling postgres pod.

### ISSUE THREAD

**Issue by saikyt** [infrahq/infra#4143] opened 2023-02-21 19:44 UTC
## Describe the bug
Self hosting infra server on K8s following these instructions https://infrahq.com/docs/reference/self-hosting
Fails to start postgress pod .

default                infra-server-864b5b87f9-f2n28               0/1     Init:0/1   0             37m
default                infra-server-postgres-0                     0/1     Pending    0             37m
default                infra-server-ui-5c45fc9b95-9dr94            1/1     Running    0             37m

## Expected behavior
All three infra pods should be in "Running" state and the load balancer should be up and running.

## Screenshots
kubectl describe pod infra-server-postgres-0
Name:           infra-server-postgres-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=infra-server
                app.kubernetes.io/name=infra-server-postgres
                controller-revision-hash=infra-server-postgres-7c9d5694dd
                statefulset.kubernetes.io/pod-name=infra-server-postgres-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/infra-server-postgres
Init Containers:
  migration:
    Image:      busybox:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
    Args:
      run() { echo "RUN: $*"; $*; }
      MOUNTPOINT=/var/lib/postgresql/data
      if [ ! -d "$MOUNTPOINT/pgdata" ]; then
        run mkdir -p $MOUNTPOINT/pgdata
        # migrate data previously stored in /var/lib/postgresql/data, exclude `pgdata` and `lost+found`
        run find $MOUNTPOINT -not -name 'pgdata' -not -name 'lost+found' -maxdepth 1 -mindepth 1 -exec mv -v {} $MOUNTPOINT/pgdata/ \;
      fi
      
    Environment:  <none>
    Mounts:
      /var/lib/postgresql/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kpl9b (ro)
Containers:
  postgres:
    Image:      postgres:14-alpine
    Port:       5432/TCP
    Host Port:  0/TCP
    Liveness:   exec [pg_isready -d infra -U infra] delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [pg_isready -d infra -U infra] delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POSTGRES_DB:        infra
      POSTGRES_USER:      infra
      POSTGRES_PASSWORD:  <set to the key 'password' in secret 'infra-server-postgres'>  Optional: false
      PGDATA:             /var/lib/postgresql/data/pgdata
    Mounts:
      /var/lib/postgresql/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kpl9b (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  infra-server-postgres
    ReadOnly:   false
  kube-api-access-kpl9b:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  17s (x9 over 40m)  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.

## Environment

```
$ infra version
```
$ ./infra version

 Client: 0.21.0
 Server: disconnected

```
$ kubectl version
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by BruceMacD** [comment] 2023-02-28 15:12
The server is failing to stand-up because the postgres deployment is failing, which it relies on. The error message indicates there are unbound persistent volume claims:
```
Warning FailedScheduling 17s (x9 over 40m) default-scheduler 0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

This could be caused by a misconfiguration. Do you have a persistent volume defined? Troubleshooting this should get things moving.

**Comment by saikyt** [comment] 2023-02-28 15:40
I do not have a PV volume defined. I was following the instructions from https://infrahq.com/docs/reference/self-hosting and did not see any step where I should be doing that.  I can create a PV manually, but need some info,  Is there a specific mount path I should be using? I am running int on a Ubuntu Host, should this be a host path? also, how much storage capacity should I allocate to Postgres? It would be great if you could share a sample YAML that you use. Thanks

**Comment by saikyt** [comment] 2023-02-28 18:59
@mxyng  this is not a managed cluster, I have K8s running on a simple Ubuntu host.

**Comment by mxyng** [comment] 2023-02-28 23:14
Do you have existing PVCs or are you able to create non-Infra PVCs? If so what storage class are they using? The default for Infra is to use the cluster default. If one doesn't exist, you can set it explicitly with `postgres.persistence.className`

**Comment by saikyt** [comment] 2023-02-28 23:22
It seems the helm chart created a PVC but there is no corresponding PV mount for it.
Should the helm chart create the PV mount as well?

kubectl describe pvc 
Name:          infra-server-postgres
Namespace:     default
StorageClass:  
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/instance=infra-server
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=infra-server-postgres
               app.kubernetes.io/version=0.21.0
               helm.sh/chart=infra-server-0.1.2
Annotations:   meta.helm.sh/release-name: infra-server
               meta.helm.sh/release-namespace: default
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       infra-server-postgres-0
Events:
  Type    Reason         Age                     From                         Message
  ----    ------         ----                    ----                         -------
  Normal  FailedBinding  2m32s (x40347 over 7d)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

**Comment by saikyt** [comment] 2023-02-28 23:23
BTW there are no other PVCs.

**Comment by mxyng** [comment] 2023-03-01 19:45
The Helm chart doesn't create a PV as it expects one to be created dynamically by the default, or configured, storage class. In EKS, this will look something like this

```
$ kubectl get storageclass
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  400d
```

For an unmanaged cluster, you'll need to set a default storage class or configure it explicitly with the Helm value I mentioned earlier. If a storage class does not exist, you'll need to create one.

Alternatively, you can create a `hostPath` PV out of band and reference it using the same Helm values.

e.g.

```yaml
# persistentvolume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-server-postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: infra-server-postgres
  hostPath:
    path: /tmp/infra-server-postgres
```

```yaml
# values.yaml
postgres:
  persistence:
    className: infra-server-postgres
```

Apply both configurations:

```bash
kubectl apply -f persistentvolume.yaml
helm install infra-server infrahq/infra-server -f values.yaml
```

A word of caution though. `hostPath` is intended for debugging/developing as it mounts a node local file/directory. If the pod gets scheduled on a different node, this persistent volume will no longer be available. An improvement on `hostPath` is `local` which requires configuring `nodeAffinity` and is not included in this example for simplicity.

**Comment by saikyt** [comment] 2023-03-02 01:37
@mxyng  That worked! thank you. However, I had to add the load balancer to the values.yaml before reInstalling with helm.
# values.yaml
server:
  service:
    type: LoadBalancer

postgres:
  persistence:
    className: infra-server-postgres

Also, how do we address the root cause here? _"The Helm chart doesn't create a PV as it expects one to be created dynamically by the default"_. Ideally, a local PV should be created dynamically. I don't know where and how that should happen. And, as you mentioned, hostPath is a temporary solution.

**Comment by mxyng** [comment] 2023-03-02 20:07
Unfortunately PVs are a highly cluster-dependent configuration. What works for one cluster may not work for another. In the case of Infra server, it delegates configuration of the PV to the user. If a default `StorageClass` is defined, the deployment should succeed without issue. If one is not defined, as in your case, the PVC storage class will need to be configured explicitly, as the example above demonstrates. This storage class may then dynamically create the PV or, in your case, reference a PV that's been created statically. There's no good defaults for the latter since `hostPath` is susceptible to pod scheduling issues while all other volume types require additional configuration or cluster knowledge.

**Comment by BruceMacD** [comment] 2023-03-06 14:20
Resolving this for now, issues with PVCs may be on a case-by-case basis as Mike notes.

Thanks for bringing this to our attention, please let us know if you face any further issues.

**Closed by BruceMacD** 2023-03-06 14:20 UTC
Labels: kind/bug

**Comment by saikyt** [comment] 2023-03-07 13:33
Thank you @BruceMacD. Can we update the documentation that a default `StorageClass` should be defined for bare metal deployments? Also, when we define `local` storage class that does not support dynamic provisioning so in some cases user will have to create a static PV.

**Comment by BruceMacD** [comment] 2023-03-07 21:13
@saikyt Great suggestion, I'll add those notes to the docs.
